if (NOT LPSOLVE_INCLUDE_DIR)
    find_path(LPSOLVE_INCLUDE_DIR lp_lib.h PATHS $ENV{${LPSOLVE_DIR}})
endif (NOT LPSOLVE_INCLUDE_DIR)

if(WIN32)
    SET(CMAKE_FIND_LIBRARY_PREFIXES "")
    SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll")
else(WIN32)
    SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
    SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")
endif(WIN32)

find_library(LPSOLVE_LIBRARY NAMES lpsolve55 PATHS ${LPSOLVE_INCLUDE_DIR})

if (NOT LPSOLVE_INCLUDE_DIR)
  MESSAGE(FATAL_ERROR "Cannot find LPSOLVE headers!")
endif (NOT LPSOLVE_INCLUDE_DIR)

if (NOT LPSOLVE_LIBRARY)
  MESSAGE(FATAL_ERROR "Cannot find LPSOLVE libraries!")
endif (NOT LPSOLVE_LIBRARY)

if (NOT LpSolve_FIND_QUIETLY)
  MESSAGE(STATUS "Found LpSolve: ${LPSOLVE_LIBRARY}")
endif (NOT LpSolve_FIND_QUIETLY)

mark_as_advanced( LPSOLVE_LIBRARY )